name: Create pre-release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - _
          - patch
          - minor
          - major
        required: false
      prerelease:
        type: choice
        options:
          - _
          - withBuildNumber
          - withoutBuildNumber
        required: false
      prelabel:
        type: choice
        options:
          - _
          - alpha
          - beta
          - rc
          - snapshot
        required: false
     
env:
  DOCKER_IMAGE_NAME: yadhav/safe-settings
  IMAGE_REGISTRY_URL: docker.io
  AZURE_RESOURCE_GROUP: aks-actions
  AZURE_AKS_CLUSTER: actionsAKSCluster
  AZURE_LOCATION: '"East US"'
  AZURE_AKS_NAMESPACE: default

jobs:
  build:
    if: ${{ github.actor != 'dependabot'}}
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.prerelease.outputs.release }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image Locally
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags:  |
            yadhav/safe-settings:main-enterprise
      - name: Inspect the Docker Image
        run: |
          docker image inspect yadhav/safe-settings:main-enterprise
      - name: Run Functional Tests
        id: functionaltest
        run: |
          docker run --env APP_ID=${{ secrets.APP_ID }} --env PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} --env WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} -d -p 3000:3000 yadhav/safe-settings:main-enterprise
          sleep 5
          curl http://localhost:3000
      - run: echo "${{ github.ref }}"
      - name: Tag a final release 
        id: prerelease
        uses: actionsdesk/semver@0.6.0-rc.10
        with:
          bump: ${{ inputs.bump }}
          prerelease: ${{ inputs.prerelease }}
          prelabel: ${{ inputs.prelabel }}
          commitish: ${{ github.ref }}
      - name: Push Docker Image
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:  |
            yadhav/safe-settings:${{ steps.prerelease.outputs.release }} 
  
 
